# Generated by Django 3.1.6 on 2021-02-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleraccount',
            name='auth_token',
            field=models.CharField(default=1, max_length=512, unique=True),
            preserve_default=False,
        ),
    ]
