# Generated by Django 3.1.6 on 2021-02-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20210209_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='meta_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
